"""Counterfactual fairness auditing for the Candidate Ranking System.

This module owns phase five of the pipeline. The :class:`CounterfactualAuditor`
builds a demographically swapped "twin" of each candidate -- swapping the
candidate name, gendered pronouns, and institution names -- and re-scores that
twin through the same scoring pipeline to detect scoring deltas that signal
demographic bias (Requirement 7).

This file provides the *pure* twin-construction surface plus the re-scoring
audit:

* :meth:`CounterfactualAuditor.swap_pronouns` -- whole-word, case-insensitive
  gendered pronoun swap (``he/him/his`` <-> ``she/her/hers``).
* :meth:`CounterfactualAuditor.swap_tokens` -- whole-word, case-insensitive
  replacement of names/institutions using a supplied mapping.
* :meth:`CounterfactualAuditor.build_twin` -- assembles the swapped resume text
  for a candidate using the configured name pairs, institution swaps, and the
  pronoun swap.
* :meth:`CounterfactualAuditor.audit` -- builds the twin, re-parses, re-enriches,
  and re-scores it through the injected collaborators (reusing the same scorer
  and vector store), computes the counterfactual delta and bias flag, updates the
  original result in place, and records the outcome in ``AUDIT_LOG``
  (Requirements 7.2-7.6, 7.9).

The three swap helpers are deterministic and perform no I/O, which keeps them
property-testable offline. Each swap is applied as a *single regex pass over an
alternation of all configured tokens* so that bidirectional swaps (for example
``he`` -> ``she`` and ``she`` -> ``he``) cannot cascade into one another. Any
token that has no configured counterpart is left unchanged (Requirement 7.1).

The swap tables (``COUNTERFACTUAL_NAME_PAIRS`` and ``INSTITUTION_SWAPS``) are
read exclusively from ``config`` so this module never redefines them
(Requirement 10.5).
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

import config

if TYPE_CHECKING:
    # Imported only for type checking so importing this module at runtime does
    # not require the heavy collaborators (``pydantic``/``ollama``/``chromadb``
    # are pulled in transitively by the models and pipeline layers) to be
    # importable. ``audit`` receives already-built collaborator instances and
    # only stores them, and the type names are used purely as annotations, which
    # ``from __future__ import annotations`` keeps unevaluated at runtime.
    from models.candidate import CandidateProfile
    from pipeline.enrich import TrajectoryEnricher
    from pipeline.ingest import ResumeParser
    from pipeline.score import CandidateScoringPipeline

logger = logging.getLogger(__name__)

#: In-memory record of counterfactual audit results. Populated by
#: :meth:`CounterfactualAuditor.audit` (one entry per audited candidate, or an
#: audit-failure entry when the twin could not be re-scored) and consumed by
#: report writing.
AUDIT_LOG: list[dict] = []

#: Filename of the persisted fairness audit report (Requirements 7.7, 7.8).
_AUDIT_REPORT_FILENAME = "bias_audit_report.json"

#: Methodology note embedded in every completed (non-skipped) audit report. It
#: documents how counterfactual twins are constructed, what the 0.75 delta
#: threshold means, and the explicit caveat that a clean result does not prove
#: the absence of bias -- only robustness to the swaps actually tested
#: (Requirement 7.7).
_METHODOLOGY_NOTE = (
    "Counterfactual twins were generated by swapping first names, gendered "
    "pronouns, and target institution names. A delta > 0.75 composite score "
    "points indicates potential sensitivity to demographic proxies and flags "
    "for human review. A clean result does not guarantee absence of bias — it "
    "indicates robustness to the specific swaps tested."
)

#: Methodology note embedded in a skipped audit report, documenting that no
#: bias analysis was performed for the run (Requirement 7.8).
_SKIPPED_METHODOLOGY_NOTE = (
    "The counterfactual fairness audit was skipped by operator request "
    "(--skip-audit); no bias analysis was performed for this run."
)


def reset_audit_log() -> None:
    """Clear the module-level :data:`AUDIT_LOG` in place.

    Empties the shared audit log without rebinding the module attribute, so any
    existing references to the list observe the cleared state. Useful for tests
    that need a clean log between audit runs; :meth:`CounterfactualAuditor.audit`
    behavior is unaffected.

    Args:
        None.

    Returns:
        None.
    """
    AUDIT_LOG.clear()

#: Bidirectional gendered-pronoun swap table, keyed by the lowercased pronoun.
#: The pairs are positional per Requirement 7.1 (he/him/his <-> she/her/hers):
#: ``he`` <-> ``she``, ``him`` <-> ``her``, ``his`` <-> ``hers``. As a
#: consequence ``her`` maps back to ``him`` and ``hers`` maps back to ``his``.
_PRONOUN_SWAPS: dict[str, str] = {
    "he": "she",
    "she": "he",
    "him": "her",
    "her": "him",
    "his": "hers",
    "hers": "his",
}


def _build_swap_pattern(keys: list[str]) -> re.Pattern[str]:
    """Compile a whole-word, case-insensitive alternation over ``keys``.

    The keys are sorted longest-first so multi-word phrases (e.g.
    ``"Imperial College"``) are matched before any shorter token they contain,
    and each key is regex-escaped and wrapped in ``\\b`` word boundaries so only
    whole words/phrases match.

    Args:
        keys: The literal tokens to match. Must be non-empty.

    Returns:
        re.Pattern[str]: A compiled, case-insensitive pattern whose single
        capturing group matches any one of ``keys`` on word boundaries.
    """
    ordered = sorted(keys, key=len, reverse=True)
    alternation = "|".join(re.escape(key) for key in ordered)
    return re.compile(rf"\b({alternation})\b", re.IGNORECASE)


def _match_case(original: str, replacement: str) -> str:
    """Reshape ``replacement`` to mirror the capitalization of ``original``.

    Preserves the most common casing patterns seen in resume prose: an all-caps
    match yields an all-caps replacement, a leading-capital match yields a
    capitalized replacement, and anything else yields a lowercase replacement.

    Args:
        original: The token as it appeared in the source text.
        replacement: The counterpart token to recase.

    Returns:
        str: ``replacement`` recased to match ``original``.
    """
    if original.isupper():
        return replacement.upper()
    if original[:1].isupper():
        return replacement.capitalize()
    return replacement.lower()


class CounterfactualAuditor:
    """Builds a demographically swapped twin of a candidate for bias auditing.

    This class exposes both the pure twin-construction surface and the
    re-scoring audit used by the counterfactual fairness audit. The static swap
    helpers depend only on their inputs (and, for names/institutions, on the
    caller-supplied mapping), so they can be exercised without a running Ollama
    server or vector store. :meth:`audit` is layered on top of those helpers: it
    re-parses, re-enriches, and re-scores the twin through the injected
    collaborators -- reusing the same scorer and vector store as the original
    candidate -- and records the resulting bias signal (Requirement 7). The
    ``write_report`` method is layered on separately.

    Attributes:
        parser: The :class:`~pipeline.ingest.ResumeParser` used to re-extract a
            :class:`~models.candidate.CandidateProfile` from the swapped twin
            text via ``parse_text`` (Requirement 7.2).
        enricher: The :class:`~pipeline.enrich.TrajectoryEnricher` used to
            re-enrich the twin profile (Requirement 7.2).
        scorer: The :class:`~pipeline.score.CandidateScoringPipeline` used to
            re-score the twin. It is the *same* instance used for the original
            candidate, so the twin is scored against the same vector store
            (Requirement 7.2).
    """

    def __init__(
        self,
        parser: ResumeParser,
        enricher: TrajectoryEnricher,
        scorer: CandidateScoringPipeline,
    ) -> None:
        """Store the collaborators used to re-evaluate a counterfactual twin.

        The three collaborators are the *same* instances used to ingest, enrich,
        and score the original candidates, so re-scoring the twin reuses the
        identical scorer and vector store and isolates the demographic swap as
        the only changed variable (Requirement 7.2).

        Args:
            parser: The :class:`~pipeline.ingest.ResumeParser` used to
                re-extract a profile from the swapped twin text.
            enricher: The :class:`~pipeline.enrich.TrajectoryEnricher` used to
                re-enrich the twin profile.
            scorer: The :class:`~pipeline.score.CandidateScoringPipeline` used
                to re-score the twin against the shared vector store.

        Returns:
            None.
        """
        self.parser = parser
        self.enricher = enricher
        self.scorer = scorer

    def audit(self, profile: CandidateProfile, result: dict) -> dict:
        """Score the twin, update ``result`` in place, and record the audit.

        Builds the demographically swapped twin text for ``profile`` via
        :meth:`build_twin`, then re-parses, re-enriches, and re-scores that twin
        through the injected collaborators using the *same* scorer and vector
        store as the original candidate, with a ``candidate_id`` of
        ``"cf_" + profile.candidate_id`` (Requirements 7.1, 7.2). The
        :data:`Counterfactual_Delta <counterfactual_delta>` is the absolute
        difference between the original and twin composite scores, rounded to two
        decimals (Requirement 7.3), and the bias flag is set when that delta
        exceeds ``config.BIAS_FLAG_THRESHOLD`` (Requirements 7.4, 7.5). The
        original ``result`` dict is mutated in place with ``bias_flag`` and
        ``counterfactual_delta`` and a corresponding entry is appended to the
        module-level :data:`AUDIT_LOG` (Requirement 7.6).

        Re-parsing/re-enriching/re-scoring the twin is wrapped in a guard: if any
        step raises (or re-extraction returns ``None``), the failure is contained
        -- ``bias_flag`` is left ``False``, ``counterfactual_delta`` is recorded
        as ``None`` (not computed), an audit-failure entry is appended to
        :data:`AUDIT_LOG`, and the method returns without re-raising so the
        remaining candidates can still be audited (Requirement 7.9).

        Args:
            profile: The original (already scored) candidate to audit. Its
                ``raw_text``, ``source_file``, ``candidate_id``, and ``name`` are
                read to build and re-parse the twin.
            result: The original candidate's score result dict (from
                :meth:`CandidateScoringPipeline.score`). Mutated in place: its
                ``bias_flag`` and ``counterfactual_delta`` keys are overwritten
                with the audit outcome.

        Returns:
            dict: The audit-log entry appended to :data:`AUDIT_LOG` -- either the
            success entry (with ``original_score``, ``cf_score``, ``delta``, and
            ``bias_flag``) or, on failure, the audit-failure entry (with
            ``audit_failure`` set and the captured ``error``).
        """
        original_composite = result["composite_score"]
        try:
            twin_text = self.build_twin(profile)

            # Re-parse the swapped twin text without touching the filesystem.
            # ``source_file`` defaults to an empty string on the model, so fall
            # back to a stable placeholder rather than ``Path("")`` (== ".").
            source_path = (
                Path(profile.source_file) if profile.source_file else Path("cf_twin")
            )
            twin_profile = self.parser.parse_text(twin_text, source_path)
            if twin_profile is None:
                raise ValueError(
                    "twin re-extraction returned no profile (validation failed "
                    "twice)"
                )
            twin_profile.candidate_id = f"cf_{profile.candidate_id}"

            twin_profile = self.enricher.enrich(twin_profile)
            cf_result = self.scorer.score(twin_profile)
            cf_composite = cf_result["composite_score"]
        except Exception as exc:  # noqa: BLE001 - contain twin failures (Req 7.9)
            logger.warning(
                "Counterfactual audit failed for candidate %s (%s); leaving "
                "bias_flag False and recording an audit-failure entry: %s",
                profile.candidate_id,
                profile.name,
                exc,
            )
            result["bias_flag"] = False
            result["counterfactual_delta"] = None
            failure_entry = {
                "candidate_id": profile.candidate_id,
                "name": profile.name,
                "original_score": result.get("composite_score"),
                "cf_score": None,
                "delta": None,
                "bias_flag": False,
                "audit_failure": True,
                "error": str(exc),
            }
            AUDIT_LOG.append(failure_entry)
            return failure_entry

        counterfactual_delta = round(abs(original_composite - cf_composite), 2)
        bias_flag = counterfactual_delta > config.BIAS_FLAG_THRESHOLD

        result["bias_flag"] = bias_flag
        result["counterfactual_delta"] = counterfactual_delta

        audit_entry = {
            "candidate_id": profile.candidate_id,
            "name": profile.name,
            "original_score": original_composite,
            "cf_score": cf_composite,
            "delta": counterfactual_delta,
            "bias_flag": bias_flag,
        }
        AUDIT_LOG.append(audit_entry)

        logger.debug(
            "Counterfactual delta for candidate %s: |%.2f - %.2f| = %.2f",
            profile.candidate_id,
            original_composite,
            cf_composite,
            counterfactual_delta,
        )
        logger.info(
            "Audited candidate %s (%s): delta=%.2f bias_flag=%s",
            profile.candidate_id,
            profile.name,
            counterfactual_delta,
            bias_flag,
        )
        return audit_entry

    def write_report(self, output_dir: Path, skipped: bool = False) -> Path:
        """Write ``bias_audit_report.json`` from :data:`AUDIT_LOG`.

        Aggregates the module-level :data:`AUDIT_LOG` into the persisted fairness
        report. Audit-failure entries (those with a truthy ``audit_failure``
        flag) are pulled out into a separate ``audit_failures`` list and are
        *not* counted toward the audited total -- only successfully re-scored
        twins contribute to ``total_candidates_audited``. The flag rate is
        ``flagged_count / total_candidates_audited`` over the successful entries,
        or ``0`` when nothing was audited (Requirement 7.7). When ``skipped`` is
        true, a report documenting that no bias analysis was performed is written
        instead, with all counts zeroed and an ``audit_skipped`` marker
        (Requirement 7.8). The destination directory is created if missing and
        the report is written with two-space indentation.

        Args:
            output_dir: Directory into which ``bias_audit_report.json`` is
                written. Created (with parents) if it does not already exist.
            skipped: When ``True``, write the audit-skipped report documenting
                that the counterfactual fairness audit was not run for this
                pass; :data:`AUDIT_LOG` is ignored. Defaults to ``False``.

        Returns:
            Path: The path to the written ``bias_audit_report.json`` file.
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        report_path = output_path / _AUDIT_REPORT_FILENAME

        if skipped:
            report: dict = {
                "total_candidates_audited": 0,
                "flagged_count": 0,
                "flag_rate": 0,
                "bias_flag_threshold": config.BIAS_FLAG_THRESHOLD,
                "flagged_candidates": [],
                "clean_candidates_count": 0,
                "methodology_note": _SKIPPED_METHODOLOGY_NOTE,
                "audit_failures": [],
                "audit_skipped": True,
            }
        else:
            # Audit failures are tracked separately and are NOT counted toward
            # the audited total; only successfully re-scored twins are
            # "audited" (Requirement 7.7).
            audit_failures = [
                entry for entry in AUDIT_LOG if entry.get("audit_failure")
            ]
            success_entries = [
                entry for entry in AUDIT_LOG if not entry.get("audit_failure")
            ]

            total_audited = len(success_entries)
            flagged_candidates = [
                {
                    "candidate_id": entry.get("candidate_id"),
                    "name": entry.get("name"),
                    "delta": entry.get("delta"),
                    "original_score": entry.get("original_score"),
                    "cf_score": entry.get("cf_score"),
                }
                for entry in success_entries
                if entry.get("bias_flag")
            ]
            flagged_count = len(flagged_candidates)
            flag_rate = flagged_count / total_audited if total_audited > 0 else 0
            clean_candidates_count = total_audited - flagged_count

            report = {
                "total_candidates_audited": total_audited,
                "flagged_count": flagged_count,
                "flag_rate": flag_rate,
                "bias_flag_threshold": config.BIAS_FLAG_THRESHOLD,
                "flagged_candidates": flagged_candidates,
                "clean_candidates_count": clean_candidates_count,
                "methodology_note": _METHODOLOGY_NOTE,
                "audit_failures": audit_failures,
            }

        with report_path.open("w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)

        logger.info(
            "Wrote fairness audit report to %s (skipped=%s, audited=%s, "
            "flagged=%s)",
            report_path,
            skipped,
            report["total_candidates_audited"],
            report["flagged_count"],
        )
        return report_path

    @staticmethod
    def swap_pronouns(text: str) -> str:
        """Swap gendered pronouns on whole-word, case-insensitive boundaries.

        Applies the bidirectional mapping ``he`` <-> ``she``, ``him`` <-> ``her``,
        ``his`` <-> ``hers`` (and therefore ``her`` -> ``him``, ``hers`` -> ``his``)
        in a single pass so the swaps do not cascade. Matching is case-insensitive
        and restricted to whole words via ``\\b`` boundaries, so substrings such
        as the ``he`` inside ``"the"`` or ``"here"`` are left untouched. The
        capitalization pattern of each match is preserved (all-caps, leading
        capital, or lowercase). Any pronoun without a configured counterpart is
        left unchanged.

        Args:
            text: The source text whose gendered pronouns should be swapped.

        Returns:
            str: ``text`` with gendered pronouns swapped to their counterparts.
        """
        pattern = _build_swap_pattern(list(_PRONOUN_SWAPS))

        def _replace(match: re.Match[str]) -> str:
            token = match.group(0)
            counterpart = _PRONOUN_SWAPS[token.lower()]
            return _match_case(token, counterpart)

        return pattern.sub(_replace, text)

    @staticmethod
    def swap_tokens(text: str, mapping: dict[str, str]) -> str:
        """Swap names/institutions using ``mapping`` on whole-word boundaries.

        Each key in ``mapping`` is replaced with its mapped value wherever it
        appears as a whole word/phrase, matched case-insensitively. All keys are
        combined into a single regex alternation (longest key first) and applied
        in one pass, so replacements never cascade -- a value that happens to
        reintroduce another key's text will not itself be re-swapped. Multi-word
        keys are matched as phrases. Tokens with no entry in ``mapping`` are left
        unchanged.

        Args:
            text: The source text in which to perform the swaps.
            mapping: Mapping of literal token (name or institution) to its
                replacement. An empty mapping leaves ``text`` unchanged.

        Returns:
            str: ``text`` with every configured token replaced by its mapped
            value.
        """
        if not mapping:
            return text

        lookup = {key.lower(): value for key, value in mapping.items()}
        pattern = _build_swap_pattern(list(mapping))

        def _replace(match: re.Match[str]) -> str:
            return lookup[match.group(0).lower()]

        return pattern.sub(_replace, text)

    def build_twin(self, profile: CandidateProfile) -> str:
        """Construct the swapped resume text for a candidate's twin.

        Operates on ``profile.raw_text`` and applies, as independent single-pass
        swaps, a bidirectional name swap built from
        ``config.COUNTERFACTUAL_NAME_PAIRS``, the institution swap
        ``config.INSTITUTION_SWAPS``, and the gendered-pronoun swap. Because the
        three swaps target disjoint token sets and each runs in a single pass,
        the order is not significant and no swap cascades into another. Any name,
        institution, or pronoun without a configured counterpart is left
        unchanged (Requirement 7.1).

        Args:
            profile: The candidate whose ``raw_text`` is transformed into the
                twin's resume text.

        Returns:
            str: The transformed resume text for the counterfactual twin.
        """
        name_map = self._bidirectional_name_map()
        twin_text = self.swap_tokens(profile.raw_text, name_map)
        twin_text = self.swap_tokens(twin_text, config.INSTITUTION_SWAPS)
        twin_text = self.swap_pronouns(twin_text)
        return twin_text

    @staticmethod
    def _bidirectional_name_map() -> dict[str, str]:
        """Expand the configured name pairs into a bidirectional swap map.

        Each ``(original, swapped)`` pair in ``config.COUNTERFACTUAL_NAME_PAIRS``
        contributes both directions (``original`` -> ``swapped`` and
        ``swapped`` -> ``original``) so the swap is symmetric. Applied via a
        single-pass alternation in :meth:`swap_tokens`, this lets a name and its
        counterpart be exchanged without cascading.

        Args:
            None.

        Returns:
            dict[str, str]: A mapping containing both swap directions for every
            configured name pair.
        """
        name_map: dict[str, str] = {}
        for original, swapped in config.COUNTERFACTUAL_NAME_PAIRS:
            name_map[original] = swapped
            name_map[swapped] = original
        return name_map
